image: python:2.7
services:
  - mysql
  - postgres
before_script:
  - apt-get update -qq
  - apt-get install -qq python-dev gcc tesseract-ocr tesseract-ocr-deu unpaper ghostscript libjpeg-dev libpng-dev libtiff-dev poppler-utils
stages:
  - build
  - test
job1:
  stage: build
  script:
    - pip install -r requirements/testing.txt
    - pip install -q mysql-python
    - pip install -q psycopg2
  only:
    - development
job2:
  stage: test
  script:
  - export TEST_APPS="acls authentication checkouts django_gpg document_indexing document_signatures documents dynamic_search folders lock_manager ocr permissions sources tags"
  - coverage run manage.py test $TEST_APPS --settings=mayan.settings.testing.base
  - coverage run manage.py test $TEST_APPS --settings=mayan.settings.testing.gitlab-ci.db_mysql
  - coverage run manage.py test $TEST_APPS --settings=mayan.settings.testing.gitlab-ci.db_postgres
  - coveralls
  only:
    - development
variables:
  POSTGRES_DB: "mayan_edms"
  POSTGRES_PASSWORD: "postgres"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "mayan_edms"
