image: python:2.7
services:
  - mysql
  - postgres
before_script:
  - apt-get update -qq
  - apt-get install -qq python-dev gcc tesseract-ocr tesseract-ocr-deu unpaper ghostscript libjpeg-dev libpng-dev libtiff-dev poppler-utils libreoffice
variables:
  POSTGRES_DB: "mayan_edms"
  POSTGRES_PASSWORD: "postgres"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "mayan_edms"
  MAYAN_TEST_APPS: "acls authentication checkouts django_gpg document_indexing document_signatures documents dynamic_search folders lock_manager metadata ocr permissions sources tags"
test:mysql:
  script:
  - pip install -r requirements/testing.txt
  - pip install -q mysql-python
  - coverage run manage.py test $MAYAN_TEST_APPS --settings=mayan.settings.testing.gitlab-ci.db_mysql --nomigrations
  - codecov
  tags:
    - mysql
test:postgres:
  script:
  - pip install -r requirements/testing.txt
  - pip install -q psycopg2
  - coverage run manage.py test $MAYAN_TEST_APPS --settings=mayan.settings.testing.gitlab-ci.db_postgres --nomigrations
  - codecov
  tags:
    - postgres
test:sqlite:
  script:
  - pip install -r requirements/testing.txt
  - coverage run manage.py test $MAYAN_TEST_APPS --settings=mayan.settings.testing.gitlab-ci --nomigrations
  - codecov
