image: python:2.7
services:
  - mysql
  - postgresql
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev gcc tesseract-ocr tesseract-ocr-deu unpaper ghostscript libjpeg-dev libpng-dev poppler-utils
  - mysql -u root -e 'create database mayan_edms;'
  - psql -c 'create database mayan_edms;' -U postgres
variables:
   - TEST_APPS: "acls authentication django_gpg document_indexing document_signatures documents dynamic_search folders lock_manager ocr permissions sources tags"
stages:
  - build
  - test
job1:
  stage: build
  script:
    - pip install -r requirements/testing.txt
    - pip install -q mysql-python
    - pip install -q psycopg2
  only:
    - development
job2:
  stage: test
  script:
  - coverage run manage.py test $TEST_APPS --settings=mayan.settings.testing.base
  - coverage run manage.py test $TEST_APPS --settings=mayan.settings.testing.travis.db_mysql
  - coverage run manage.py test $TEST_APPS --settings=mayan.settings.testing.travis.db_postgres
  - coveralls
  only:
    - development
