stages:
  - test
  - build_python
  - build_docker
  - build_documentation
  - push_python
  - push_docker
  - push_documentation
  - deploy

# Docker

job_docker_build:
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  image: docker:latest
  only:
    - releases/all
    - releases/docker
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" -f docker/Dockerfile .
    - DOCKER_VERSION=`cat docker/rootfs/version`
    - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE:$DOCKER_VERSION"
    - SERVICE_POSTGRES_IP=$(cat /etc/hosts | awk '{if ($2 == "postgres") print $1;}')
    - docker run --rm --add-host="postgres:$SERVICE_POSTGRES_IP" -e MAYAN_DATABASES="{'default':{'ENGINE':'django.db.backends.postgresql_psycopg2','NAME':'mayan_edms','USER':'postgres','PASSWORD':'postgres','HOST':'postgres'}}" "$CI_REGISTRY_IMAGE:$DOCKER_VERSION" run_tests
    - docker push "$CI_REGISTRY_IMAGE:$DOCKER_VERSION"
    - docker logout
  services:
    - docker:dind
    - postgres:9.6-alpine
  stage: build_docker
  tags:
    - postgres
  variables:
    POSTGRES_DB: "mayan_edms"
    POSTGRES_PASSWORD: "postgres"

job_docker_push_major:
  before_script:
    - apk add --no-cache python3
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  image: docker:latest
  only:
    - releases/all
    - releases/docker
  script:
    - PYTHON_BIN=/usr/bin/python3
    - DOCKER_VERSION=`cat docker/rootfs/version`
    - docker pull "$CI_REGISTRY_IMAGE:$DOCKER_VERSION"
    - docker tag "$CI_REGISTRY_IMAGE:$DOCKER_VERSION" registry-1.docker.io/mayanedms/mayanedms:v"$DOCKER_VERSION"
    - docker tag "$CI_REGISTRY_IMAGE:$DOCKER_VERSION" registry-1.docker.io/mayanedms/mayanedms:latest
    - VERSION_SCRIPT_BIN=contrib/scripts/version.py
    - MAJOR_VERSION=$($PYTHON_BIN $VERSION_SCRIPT_BIN $DOCKER_VERSION major);
    - docker tag "$CI_REGISTRY_IMAGE:$DOCKER_VERSION" registry-1.docker.io/mayanedms/mayanedms:s"$MAJOR_VERSION"
    - MINOR_VERSION=$($PYTHON_BIN $VERSION_SCRIPT_BIN $DOCKER_VERSION minor);
    - docker tag "$CI_REGISTRY_IMAGE:$DOCKER_VERSION" registry-1.docker.io/mayanedms/mayanedms:s"$MINOR_VERSION"
    - docker logout
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD" https://registry-1.docker.io
    - docker push registry-1.docker.io/mayanedms/mayanedms:v"$DOCKER_VERSION"
    - docker push registry-1.docker.io/mayanedms/mayanedms:latest
    - docker push registry-1.docker.io/mayanedms/mayanedms:s"$MAJOR_VERSION"
    - docker push registry-1.docker.io/mayanedms/mayanedms:s"$MINOR_VERSION"
  stage: push_docker
  services:
    - docker:dind

job_docker_push_minor:
  before_script:
    - apk add --no-cache python3
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  image: docker:latest
  only:
    - releases/all_minor
    - releases/docker_minor
  script:
    - PYTHON_BIN=/usr/bin/python3
    - DOCKER_VERSION=`cat docker/rootfs/version`
    - docker pull "$CI_REGISTRY_IMAGE:$DOCKER_VERSION"
    - docker tag "$CI_REGISTRY_IMAGE:$DOCKER_VERSION" registry-1.docker.io/mayanedms/mayanedms:v"$DOCKER_VERSION"
    - docker tag "$CI_REGISTRY_IMAGE:$DOCKER_VERSION" registry-1.docker.io/mayanedms/mayanedms:latest
    - VERSION_SCRIPT_BIN=contrib/scripts/version.py
    - MINOR_VERSION=$($PYTHON_BIN $VERSION_SCRIPT_BIN $DOCKER_VERSION minor);
    - docker tag "$CI_REGISTRY_IMAGE:$DOCKER_VERSION" registry-1.docker.io/mayanedms/mayanedms:s"$MINOR_VERSION"
    - docker logout
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD" https://registry-1.docker.io
    - docker push registry-1.docker.io/mayanedms/mayanedms:v"$DOCKER_VERSION"
    - docker push registry-1.docker.io/mayanedms/mayanedms:latest
    - docker push registry-1.docker.io/mayanedms/mayanedms:s"$MINOR_VERSION"
  stage: push_docker
  services:
    - docker:dind

job_docker_nightly:
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  image: docker:latest
  only:
    - releases/nightly
    - releases/staging
  services:
    - docker:dind
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" -f docker/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker logout
  stage: build_docker

job_docker_testing:
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  image: docker:latest
  only:
    - releases/testing
  script:
    - PYTHON_BIN=/usr/bin/python3
    - DOCKER_VERSION=`cat docker/rootfs/version`
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$DOCKER_VERSION" -f docker/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:$DOCKER_VERSION"
    - docker logout
  services:
    - docker:dind
  stage: build_docker

# Documentation

job_documentation_build:
  artifacts:
    expire_in: 2 hr
    paths:
    - docs
  before_script:
    - apt-get -qq update
    - apt-get install -qq enchant make python-dev python-virtualenv python3-dev
    - virtualenv venv -p /usr/bin/python3
    - . venv/bin/activate
  image: ubuntu:19.10
  only:
    - releases/all
    - releases/documentation
  script:
    - pip install -r requirements/documentation.txt
    - cd docs
    - make html
  stage: build_documentation

job_documentation_push:
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$DOCUMENTATION_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client rsync -y )'
    - eval $(ssh-agent -s)
    - echo "$DOCUMENTATION_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - ssh mayandocs@docs.mayan-edms.com "rm -Rf /home/rosarior/webapps/mayan_docs/*"
    - rsync -avzP --progress -e ssh docs/_build/html/* mayandocs@docs.mayan-edms.com:/home/rosarior/webapps/mayan_docs
  image: ubuntu:19.10
  only:
    - releases/all
    - releases/documentation
  stage: push_documentation

# Python

job_build_python:
  artifacts:
    expire_in: 2 hr
    paths:
    - dist
  before_script:
    - apt-get -qq update
    - apt-get install -qq make python-dev python-virtualenv python3-dev
    - virtualenv venv -p /usr/bin/python3
    - . venv/bin/activate
  image: ubuntu:19.10
  only:
    - releases/all
    - releases/all_minor
    - releases/python
  script:
    - pip install -r requirements/build.txt
    - make python-wheel
  stage: build_python

job_push_python:
  before_script:
    - apt-get -qq update
    - apt-get install -qq make python-dev python-virtualenv python3-dev
    - virtualenv venv -p /usr/bin/python3
    - . venv/bin/activate
  image: ubuntu:19.10
  only:
    - releases/all
    - releases/all_minor
    - releases/python
  script:
    - pip install -r requirements/build.txt
    - echo "$PYPIRC" > ~/.pypirc
    - twine upload dist/* -r pypi
  stage: push_python

# Test upgrade from the latest public version to the local version

.test_upgrade_base: &test_upgrade_base
  before_script:
    - set -a && . ./config.env && set +a
    - apt-get -qq update
    - apt-get install -qq curl exiftool gcc ghostscript gnupg1 libjpeg-dev libmagic1 libpng-dev libtiff-dev make poppler-utils python-dev python-virtualenv python3-dev tesseract-ocr
    - virtualenv venv -p /usr/bin/python3
    - . venv/bin/activate
    - DOCKER_VERSION=`cat docker/rootfs/version`
    - pip install "mayan-edms<$DOCKER_VERSION"
    - pip install -r requirements/build.txt -r requirements/testing-base.txt
    - pip install django-test-without-migrations==0.6
    - make python-wheel
  cache:
    paths:
      - ~/.cache/pip/
      - /var/cache/apt/archives/
  image: ubuntu:19.10
  only:
    - releases/all
    - releases/all_minor
    - releases/docker
    - releases/docker_minor
    - releases/python
    - releases/python_minor
    - releases/staging
  stage: test

test_upgrade_sqlite:
  <<: *test_upgrade_base
  script:
    - . venv/bin/activate
    - mayan-edms.py initialsetup --settings=mayan.settings.testing.gitlab-ci
    - pip install dist/mayan_edms-*.whl
    - mayan-edms.py performupgrade --settings=mayan.settings.testing.gitlab-ci

test_upgrade_mysql:
  <<: *test_upgrade_base
  services:
    - mysql:5.7
  script:
    - apt-get install -qq libmysqlclient-dev libssl-dev mysql-client
    - . venv/bin/activate
    - pip install mysqlclient==$PYTHON_MYSQL_VERSION
    - mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD" -e "set global character_set_server=utf8mb4;"
    - mayan-edms.py initialsetup --settings=mayan.settings.testing.gitlab-ci.db_mysql
    - pip install dist/mayan_edms-*.whl
    - mayan-edms.py performupgrade --settings=mayan.settings.testing.gitlab-ci.db_mysql
  tags:
    - mysql
  variables:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    MYSQL_DATABASE: "mayan_edms"

test_upgrade_postgres:
  <<: *test_upgrade_base
  variables:
    POSTGRES_DB: "mayan_edms"
    POSTGRES_PASSWORD: "postgres"
  services:
    - postgres:9.6-alpine
  script:
    - apt-get install -qq libpq-dev
    - . venv/bin/activate
    - pip install psycopg2==$PYTHON_PSYCOPG2_VERSION
    - mayan-edms.py initialsetup --settings=mayan.settings.testing.gitlab-ci.db_postgres
    - pip install dist/mayan_edms-*.whl
    - mayan-edms.py performupgrade --settings=mayan.settings.testing.gitlab-ci.db_postgres
  tags:
    - postgres

# Run the test suit

.test_base: &test_base
  before_script:
    - set -a && . ./config.env && set +a
    - apt-get -qq update
    - apt-get install -qq curl exiftool firefox-geckodriver gcc ghostscript gnupg1 graphviz libfuse2 libjpeg-dev libmagic1 libpng-dev libtiff-dev libreoffice make poppler-utils python-dev python-virtualenv python3-dev sane-utils tesseract-ocr tesseract-ocr-deu
    - virtualenv venv -p /usr/bin/python3
    - . venv/bin/activate
    - pip install -r requirements.txt -r requirements/testing-base.txt
  cache:
    paths:
      - ~/.cache/pip/
      - /var/cache/apt/archives/
  image: ubuntu:19.10
  only:
    - releases/all
    - releases/all_minor
    - releases/docker
    - releases/docker_minor
    - releases/python
    - releases/python_minor
    - releases/staging
  stage: test

test-postgres:
  <<: *test_base
  script:
    - apt-get install -qq libpq-dev
    - . venv/bin/activate
    - pip install psycopg2==$PYTHON_PSYCOPG2_VERSION
    - make test-all SETTINGS=mayan.settings.testing.gitlab-ci.db_postgres
    - make test-all-migrations SETTINGS=mayan.settings.testing.gitlab-ci.db_postgres
  services:
    - postgres:9.6-alpine
  tags:
    - postgres
  variables:
    POSTGRES_DB: "mayan_edms"
    POSTGRES_PASSWORD: "postgres"

test-sqlite:
  <<: *test_base
  script:
    - . venv/bin/activate
    - python manage.py test --mayan-apps --settings=mayan.settings.testing.gitlab-ci --skip-migrations
    - make test-all
    - make test-all-migrations

# Deploy

deploy_demo:
  before_script:
    - mkdir -p ~/.ssh
    - echo "${DEMO_SSH_KNOWN_HOST}" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "${DEMO_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  environment:
    name: demo
  script:
    - scp contrib/scripts/install/docker.sh root@$DEMO_IP_ADDRESS:~
    - ssh root@$DEMO_IP_ADDRESS "DELETE_VOLUMES=true ./docker.sh"
  stage: deploy
  when: manual

deploy_staging:
  before_script:
    - mkdir -p ~/.ssh
    - echo "${STAGING_SSH_KNOWN_HOST}" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "${STAGING_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  environment:
    name: staging
  script:
    - scp contrib/scripts/install/docker.sh root@$STAGING_IP_ADDRESS:~
    - ssh root@$STAGING_IP_ADDRESS "DOCKER_MAYAN_IMAGE=registry.gitlab.com/mayan-edms/mayan-edms:staging ./docker.sh"
  stage: deploy
  when: manual
