language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  global:
   - TEST_APPS="document_indexing documents dynamic_search lock_manager document_signatures folders ocr tags"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev gcc tesseract-ocr unpaper ghostscript libjpeg-dev libpng-dev poppler-utils
install:
  - "pip install -r requirements/testing.txt"
before_script:
  - "python manage.py initialsetup"
script:
  - coverage run manage.py test $TEST_APPS
after_success:
  - coveralls
branches:
  only:
    - master
    - development
notifications:
  email:
    recipients:
    - roberto.rosario@mayan-edms.com
    on_success: never
    on_failure: always
matrix:
  allow_failures:
    - python: 3.2
    - python: 3.3
    - python: 3.4


