language: python
python:
  - 2.7
  - 2.6
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev gcc tesseract-ocr unpaper ghostscript libjpeg-dev libpng-dev poppler-utils
install:
  - "pip install -r requirements/testing.txt"
script:
  - coverage run --source=document_indexing,documents,document_signatures,dynamic_search,lock_manager,folders,ocr,tags manage.py test document_indexing documents dynamic_search lock_manager document_signatures folders ocr tags
after_success:
  - coveralls
branches:
  only:
    - master
    - development
notifications:
  email:
    recipients:
    - roberto.rosario@mayan-edms.com
    on_success: never
    on_failure: always
