version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mayan
      POSTGRES_PASSWORD: mayan-password
      POSTGRES_USER: mayan

  app:
    image: registry.gitlab.com/mayan-edms/mayan-edms
    restart: always
    ports:
      - 8000:8000
    environment:
      MAYAN_DATABASE_DRIVER: django.db.backends.postgres
      MAYAN_DATABASE_HOST: db
      MAYAN_DATABASE_NAME: mayan
      MAYAN_DATABASE_PASSWORD: mayan-password
      MAYAN_DATABASE_USER: mayan

