version: '3.1'

volumes:
    app:
        driver: local
    db:
        driver: local

services:

  db:
    environment:
      POSTGRES_DB: mayan
      POSTGRES_PASSWORD: mayandbpass
      POSTGRES_USER: mayan
    image: postgres:10.14-alpine
    volumes:
      - db:/var/lib/postgresql/data

  app:
    environment:
      MAYAN_CELERY_BROKER_URL: redis://redis:6379/1
      MAYAN_CELERY_RESULT_BACKEND: redis://redis:6379/0
      MAYAN_DATABASES: "{'default':{'ENGINE':'django.db.backends.postgresql','NAME':'mayan','PASSWORD':'mayandbpass','USER':'mayan','HOST':'db'}}"
    image: mayanedms/mayanedms:latest
    ports:
      - 80:8000
    volumes:
      - app:/var/lib/mayan

  redis:
    command:
      - redis-server
      - --appendonly
      - "no"
      - --databases
      - "2"
      - --maxmemory-policy
      - allkeys-lru
      - --save
      - ""
    image: redis:5.0-alpine
